### ISSUE TITLE
Same slug overrides older article

### ISSUE THREAD

**Issue by OmitNomis** [uzura89/easy-blog-template#1]
If i already have an article with slug = `title`
and i create another post with the same slug, it just replaces my previous post. 

we can maybe add some numbering like `title1` to the newer slug. 
or maybe have a validation while typing in slug

**Comment by uzura89** [comment]
Hi Simon,

Thank you for pointing this out.
Right, I just updated the code.
Now, it will automatically add the numbering "-1" on the bottom instead of
overwriting it.

Thanks! Hope it works.

Yuya

2023年10月5日(木) 1:56 Simon Poudyal ***@***.***>:

**Comment by OmitNomis** [comment]
Looks like the issue with replacing the older article is fixed. Thanks
